/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ProposalGovernor } from "./ProposalGovernor";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { ProposalGovernor__factory } from "./factories/ProposalGovernor__factory";
